app:
  build: .
  ports:
    - "8080:8080"
  links:
    - mariadb
    - redis
  volumes:
    - ".:/go/src/app"
  volumes_from:
    - gopath
  command: go run main.go

mariadb:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: password
redis:
  image: redis
gopath:
  image: busybox

